CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow OWNER airflow;

CREATE USER nifi WITH PASSWORD 'nifi';
CREATE DATABASE nifi OWNER nifi;

CREATE USER superset WITH PASSWORD 'superset';
CREATE DATABASE superset OWNER superset;